services:
  - type: web
    name: ari-webapp
    env: node
    region: oregon
    plan: starter
    buildCommand: pnpm install && pnpm npx prisma generate && pnpm build
    startCommand: pnpm start
    healthCheckPath: /api/_health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_BASE_URL
        sync: false
      - key: NEXT_PUBLIC_PRIVY_APP_ID
        sync: false
      - key: PRIVY_APP_SECRET
        sync: false
      - key: WALLET_ENCRYPTION_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: ari-db
          property: connectionString
      - key: DIRECT_URL
        fromDatabase:
          name: ari-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_BASE_URL
        value: https://api.openai.com/v1
      - key: OPENAI_MODEL_NAME
        value: gpt-3.5-turbo
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: HELIUS_API_KEY
        sync: false
      - key: NEXT_PUBLIC_HELIUS_RPC_URL
        sync: false
      - key: NEXT_PUBLIC_IMGBB_API_KEY
        sync: false
      - key: NEXT_PUBLIC_MAINTENANCE_MODE
        value: false
      - key: NEXT_PUBLIC_DEBUG_MODE
        value: false
      - key: NEXT_PUBLIC_EAP_RECEIVE_WALLET_ADDRESS
        sync: false
      - key: PRIVY_SIGNING_KEY
        sync: false
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1

databases:
  - name: ari-db
    plan: starter
    region: oregon
    postgresMajorVersion: 15
    ipAllowList: [] 